#pragma config(Motor,  port2,           rightF,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftF,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftB,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rampMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           upArmMotorR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           upArmMotorL,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           armMotor,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void rampMove(){
	if (vexRT[Btn7U] == 1){
			motor[rampMotor] = 100;
	}
	else if (vexRT[Btn7D] == 1){
			motor[rampMotor] = -100;
	}

	else{
		motor[rampMotor] = 0;
	}
}

void armMovement(){
		if (vexRT[Btn6U] == 1){
			motor[armMotor] = 80;
		}
		else if (vexRT[Btn6D] == 1){
			motor[armMotor] = -80;
		}
		else {
			motor[armMotor] = 0;
		}
}

void armMoveBox(){
	if (vexRT[Btn5U] == 1){
			motor[upArmMotorR] = 120;
			motor[upArmMotorL
			] = 120;
		}
		else if (vexRT[Btn5D] == 1){
			motor[upArmMotorR] = -120;
			motor[upArmMotorL] = -120;
		}
		else {
			motor[upArmMotorR] = 0;
			motor[upArmMotorL] = 0;
		}
}

task main()
{
	while (1 == 1){
		//Movement Control
		motor[rightF] = vexRT[Ch2];
		motor[rightB] = vexRT[Ch2];
		motor[leftF] = vexRT[Ch3];
		motor[leftB] = vexRT[Ch3];

		//Control the 2 arm motors
		armMoveBox();

		//Control the arm up and down
		armMovement();

		//Ramp Thrust
		rampMove();
	}
}
